language: objective-c
osx_image: xcode9

cache:
  directories:
  - Carthage

matrix:
  include:
    - before_install:
        - carthage bootstrap --verbose --platform iOS --no-use-binaries --cache-builds
      script:
        - xcodebuild clean build test -project SwiftyJSONModel.xcodeproj -scheme SwiftyJSONModel -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 8 Plus'
      env: CACHE_NAME=IOS

    - before_install:
        - carthage bootstrap --verbose --platform tvOS --no-use-binaries --cache-builds
      script:
        - xcodebuild clean build test -project SwiftyJSONModel.xcodeproj -scheme SwiftyJSONModel-tvOS -destination 'platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p'
      env: CACHE_NAME=TV_OS

    - before_install:
        - carthage bootstrap --verbose --platform Mac --no-use-binaries --cache-builds
      script:
        - xcodebuild clean build test -project SwiftyJSONModel.xcodeproj -scheme SwiftyJSONModel-Mac
      env: CACHE_NAME=MAC

    - before_install:
        - carthage bootstrap --verbose --no-use-binaries --platform watchOS --cache-builds
      script:
        - xcodebuild clean build -project SwiftyJSONModel.xcodeproj -scheme SwiftyJSONModel-watchOS
      env: CACHE_NAME=WATCH_OS

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
